version: '3.8'
services:
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - ./backend:/app:rw 

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
